rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 86400       #1天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: magazine123      #md5加密混淆key

server:
  port: 8080 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      url: jdbc:mysql://39.108.239.82:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: root
      password: uAiqwVwjJ8-i
      filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns-rest.log


#微信配置
wx:
 # 公众号
  subscription:
    appid:
    secret:
    token:
    aesKey:
    msgDataFormat: JSON
  # 小程序
  small-program:
    appid: wx13aa51d90f49a3d6
    secret: 3fa018be939b187b95a6a8915a133b88
    token:
    aesKey:
    msgDataFormat: JSON
  # 微信支付
  wx-pay:
    #微信公众号或者小程序等的appid
    appId: wx13aa51d90f49a3d6
    #微信支付商户号
    mchId: 1506739701
    #微信支付商户密钥
    mchKey: 5A8D5BCE2F1C56A9C2E4331CE016FD58
    #服务商模式下的子商户公众账号ID
    subAppId:
    #服务商模式下的子商户号
    subMchId:
    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    keyPath: classpath:/apiclient_cert.p12